name = "kingsleague"
main = "api/index.js"
compatibility_date = "2023-01-05"

[site]
bucket = "./assets"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "kingsleague.jonanv.workers.dev", custom_domain = true }
]