# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Scrape Kings League Infojobs Website

on:
  workflow_dispatch:
  
  repository_dispatch:
    types: 
      - webhook
  
  schedule:
    - cron: "0 */1 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.22.0
          run_install: true
      - run: |
          node scraping/leaderboard.js
          git config user.name kingsleague-bot
          git add -A
          git commit -m "[bot] :zap: Update Kings League Database"
          git push origin main
