name: Scrape Kings League Infojobs Website

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "0 */1 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.1
          run_install: true
      - run: |
          npm run scrape
          git config user.name kingsleague-bot
          git config user.email jonan-vargas23@hotmail.com
          git add -A
          git commit -m "[bot] :zap: Update Kings League Database"
          git push origin main
